[package]
name = "warlock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.8.2"
solana-client = "1.8.2"
solana-sdk = "1.8.2"
quarry-mine = "1.10.0"
anchor-client = "0.18.0"