use crate::utils::*;
use crate::MinerWrapper;
use anchor_client::anchor_lang::AccountDeserialize;
use axum::{http::StatusCode, Json};
use quarry_mine::{Miner, Quarry};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use solana_program::pubkey::Pubkey;
use solana_sdk::{account::Account, program_error::ProgramError};
use tracing::Level;
